package net.lll0.bus.database.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import net.lll0.bus.database.entity.CollectionBusLineEntity;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig collectionBusLineEntityDaoConfig;

    private final CollectionBusLineEntityDao collectionBusLineEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        collectionBusLineEntityDaoConfig = daoConfigMap.get(CollectionBusLineEntityDao.class).clone();
        collectionBusLineEntityDaoConfig.initIdentityScope(type);

        collectionBusLineEntityDao = new CollectionBusLineEntityDao(collectionBusLineEntityDaoConfig, this);

        registerDao(CollectionBusLineEntity.class, collectionBusLineEntityDao);
    }
    
    public void clear() {
        collectionBusLineEntityDaoConfig.getIdentityScope().clear();
    }

    public CollectionBusLineEntityDao getCollectionBusLineEntityDao() {
        return collectionBusLineEntityDao;
    }

}
